spring:
  application:
    name: account-service
  datasource:
    url: jdbc:postgresql://localhost:5432/brickstore-dev
    username: alex
    password: test123
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: create
  security:
    oauth2:
      resourceId: account-service
      clientId: brickstore-client-prototype
      userInfoEndpointUrl: http://localhost:8095/user/me
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
    registry-fetch-interval-seconds: 10

server:
  port: 8100

#logging:
#  level:
#    root: INFO
#    org.springframework.web: INFO
#    org.springframework.web.HttpLogging: DEBUG
#    org.springframework.security: DEBUG
#    org.springframework.security.oauth2: DEBUG
springdoc:
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  show-actuator: true



