eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka/

spring:
  data:
    mongodb:
      host: mongo-db
      port: 27017
      database: order-service-db
  rabbitmq:
    host: rabbitmq
  security:
    oauth2:
      resourceId: order-service
      clientId: brickstore-client-prototype
      userInfoEndpointUrl: http://gateway:8080/user/me
