version: '3.4'
services:
  postgres-db:
    image: "postgres"
    ports:
      - "6000:5432"
    environment:
      - POSTGRES_USER=alex
      - POSTGRES_PASSWORD=test123
      - POSTGRES_DB=brickstore-dev
  discovery-service:
    build: ./discovery-service
    container_name: discovery-service
    image: discovery-service:latest
    expose:
      - "8761"
    ports:
      - "8761:8761"
  oauth-server:
    build: ./oauth-server
    container_name: oauth-server
    image: oauth-server:latest
    expose:
      - "8095"
    ports:
      - "8095:8095"
    depends_on:
      - postgres-db
    environment:
      - "SPRING_PROFILES_ACTIVE=docker-compose"
  gateway:
    build: ./api-gateway
    container_name: gateway
    image: api-gateway:latest
    expose:
      - "8080"
    ports:
      - "8080:8080"
    depends_on:
      - discovery-service
    environment:
      - "SPRING_PROFILES_ACTIVE=docker-compose"

  http-based-account-service:
    build: ./http-based-prototype/http-based-account-service
    container_name: http-based-account-service
    image: http-based-account-service:latest
    expose:
      - "8100"
    ports:
      - "8100:8100"
    depends_on:
      - discovery-service
    environment:
      - "SPRING_PROFILES_ACTIVE=docker-compose"
  http-based-inventory-service:
    build: ./http-based-prototype/http-based-inventory-service
    container_name: http-based-inventory-service
    image: http-based-inventory-service:latest
    expose:
      - "8101"
    ports:
      - "8101:8101"
    depends_on:
      - discovery-service
    environment:
      - "SPRING_PROFILES_ACTIVE=docker-compose"
  http-based-order-service:
    build: ./http-based-prototype/http-based-order-service
    container_name: http-based-order-service
    image: http-based-order-service:latest
    expose:
      - "8103"
    ports:
      - "8103:8103"
    depends_on:
      - discovery-service
    environment:
      - "SPRING_PROFILES_ACTIVE=docker-compose"
  http-based-shopping-cart-service:
    build: ./http-based-prototype/http-based-shopping-cart-service
    container_name: http-based-shopping-cart-service-service
    image: http-based-shopping-cart-service-service:latest
    expose:
      - "8102"
    ports:
      - "8102:8102"
    depends_on:
      - discovery-service
    environment:
      - "SPRING_PROFILES_ACTIVE=docker-compose"
