
spring:
  cloud:
    gateway:
      routes:
        - id: demo-service
          uri: lb://demo-service/
          predicates:
            - Path=/demo/**
          filters:
            - RewritePath=/demo/(?<segment>.*), /$\{segment}
            - TokenRelay=
            - RemoveRequestHeader=Cookie
