
spring:
  application:
    name: api-gateway

server:
  port: 8080
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
    registry-fetch-interval-seconds: 10

management:
  endpoints:
    web:
      exposure:
        include: "*"

springdoc:
  swagger-ui:
    operations-sorter: method
    oauth:
      client-id: brickstore-client-prototype
      client-secret: clientSecretPrototype
    urls[0]:
      name: accounts
      url: /accounts/v3/api-docs
    urls[1]:
      name: inventory
      url: /inventory/v3/api-docs
    urls[2]:
      name: orders
      url: /orders/v3/api-docs
    urls[3]:
      name: shopping cart
      url: /shopping-carts/v3/api-docs

    #logging:
    #  level:
    #    org.springframework.cloud.gateway: DEBUG
    #    root: INFO
#    org.springframework.web: trace
#    org.springframework.web.HttpLogging: DEBUG
#    org.springframework.security: DEBUG
#    org.springframework.security.oauth2: DEBUG
