
spring:
  cloud:
    gateway:
      routes:
        - id: account-service
          uri: lb://account-service/
          predicates:
            - Path=/accounts/**
          filters:
#            - TokenRelay=
            - RemoveRequestHeader=Cookie
        - id: inventory-service
          uri: lb://inventory-service/
          predicates:
            - Path=/inventory/**
          filters:
#            - TokenRelay=
            - RemoveRequestHeader=Cookie
