
spring:
  cloud:
    gateway:
      routes:
        - id: account-service
          uri: lb://account-service/
          predicates:
            - Path=/accounts/**,/events/**
          filters:
            - RewritePath=/accounts/actuator/(?<segment>.*), /actuator/$\{segment}
            #            - TokenRelay=
            - RemoveRequestHeader=Cookie
        - id: inventory-service
          uri: lb://inventory-service/
          predicates:
            - Path=/inventory/**
          filters:
            - RewritePath=/inventory/actuator/(?<segment>.*), /actuator/$\{segment}
            #            - TokenRelay=
            - RemoveRequestHeader=Cookie
        - id: shopping-cart-service
          uri: lb://shopping-cart-service/
          predicates:
            - Path=/shopping-carts/**
          filters:
            - RewritePath=/shopping-carts/actuator/(?<segment>.*), /actuator/$\{segment}
            #            - TokenRelay=
            - RemoveRequestHeader=Cookie
        - id: order-service
          uri: lb://order-service/
          predicates:
            - Path=/orders/**
          filters:
            - RewritePath=/orders/actuator/(?<segment>.*), /actuator/$\{segment}
            #            - TokenRelay=
            - RemoveRequestHeader=Cookie
