spring:
  application:
    name: order-service
  data:
    mongodb:
      host: localhost
      port: 27017
      database: order-service-db
  #      password: admin
  #      username: adminpwd
  #      authentication-database: auth_db
  jpa:
    hibernate:
      ddl-auto: create
  security:
    oauth2:
      resourceId: order-service
      clientId: brickstore-client-prototype
      userInfoEndpointUrl: http://localhost:8080/user/me
  gateway:
    host: localhost
    port: 8080
    scheme: http

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
    registry-fetch-interval-seconds: 10
server:
  port: 8103

springdoc:
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  show-actuator: true
#logging:
#  level:
#    root: INFO
#    org.springframework.web: INFO
#    org.springframework.web.HttpLogging: DEBUG
#    org.springframework.security: DEBUG
#    org.springframework.security.oauth2: DEBUG



