spring:
  application:
    name: order-service
  data:
    mongodb:
      host: localhost
      port: 27017
      database: order-service-db
  #      password: admin
  #      username: adminpwd
  #      authentication-database: auth_db
  jpa:
    hibernate:
      ddl-auto: create

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
    registry-fetch-interval-seconds: 10
server:
  port: 8103

management:
  endpoints:
    web:
      exposure:
        include: "*"

#logging:
#  level:
#    root: INFO
#    org.springframework.web: INFO
#    org.springframework.web.HttpLogging: DEBUG
#    org.springframework.security: DEBUG
#    org.springframework.security.oauth2: DEBUG



