spring:
  application:
    name: shopping-cart-service
  data:
    mongodb:
      host: localhost
      port: 27017
      database: shopping-cart-service-db
  #      password: admin
  #      username: adminpwd
  #      authentication-database: auth_db
  jpa:
    hibernate:
      ddl-auto: create
  security:
    oauth2:
      resourceId: shopping-cart-service
      clientId: brickstore-client-prototype
      userInfoEndpointUrl: http://localhost:8095/user/me

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
    registry-fetch-interval-seconds: 10
server:
  port: 8102

springdoc:
  swagger-ui:
    operations-sorter: method
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  show-actuator: true

#logging:
#  level:
#    root: INFO
#    org.springframework.web: INFO
#    org.springframework.amqp: DEBUG
#    org.springframework.web.HttpLogging: DEBUG
#    org.springframework.security: DEBUG
#    org.springframework.security.oauth2: DEBUG



