eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka/

spring:
  datasource:
    url: jdbc:postgresql://postgres-db:5432/brickstore-dev
    username: alex
    password: test123
  security:
    oauth2:
      resourceId: shopping-cart-service
      clientId: brickstore-client-prototype
      userInfoEndpointUrl: http://gateway:8080/user/me
