spring:
  application:
    name: inventory-service
  data:
    mongodb:
      host: localhost
      port: 27017
      database: inventory-service-db
      uri: mongodb://localhost:27017/inventory-service-db?replicaSet=rs0
  #      password: admin
  #      username: adminpwd
  #      authentication-database: auth_db
  jpa:
    hibernate:
      ddl-auto: create
  security:
    oauth2:
      userInfoEndpointUrl: http://localhost:8080/user/me
  gateway:
    host: localhost
    port: 8080
    scheme: http

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
    registry-fetch-interval-seconds: 10

server:
  port: 8101

springdoc:
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  show-actuator: true

#logging:
#  level:
#    root: INFO
#    org.springframework.data.mongodb: DEBUG
#    org.springframework.web: INFO
#    org.springframework.web.HttpLogging: DEBUG
#    org.springframework.security: DEBUG
#    org.springframework.security.oauth2: DEBUG



