spring:
  application:
    name: demo-microservice

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    defaultZone: http://localhost:8761/eureka/

okta:
  oauth2:
    issuer: https://dev-720149.okta.com/oauth2/default
    groups-claim: groups
    audience: api://default
---
spring:
  profiles: demo-instance1

server:
  port: 9000

---
spring:
  profiles: demo-instance2

server:
  port: 9002
