spring:
  application:
    name: demo-service
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://dev-720149.okta.com/oauth2/default/v1/keys

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
    registry-fetch-interval-seconds: 10

#logging:
#  level:
#    root: INFO
#    org.springframework.web: INFO
#    org.springframework.web.HttpLogging: DEBUG
#    org.springframework.security: DEBUG
#    org.springframework.security.oauth2: DEBUG
---
spring:
  profiles: demo-instance1

server:
  port: 9000

---
spring:
  profiles: demo-instance2

server:
  port: 9002
---

