spring:
  application:
    name: oauth-server
  datasource:
    url: jdbc:postgresql://localhost:5432/brickstore-dev
    username: alex
    password: test123
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: create

  security:
    oauth2:
      resourceId: auth-server
server:
  port: 8095

security:
  jwt:
    signing-key: superDuberSecretKey
  bcrypt:
    strength: 4

#logging:
#  level:
#    root: INFO
#    org.springframework.web: INFO
#    org.springframework.web.HttpLogging: DEBUG
#    org.springframework.security: DEBUG
#    org.springframework.security.oauth2: DEBUG
